# Generated by Django 3.1.2 on 2020-10-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myagri', '0002_auto_20201013_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
